@startuml
'https://plantuml.com/class-diagram

package ucf.assignments{

    GuiController *-- tdItem
    App -- GuiController

    +Class App{
    +start(Stage stage)
    +{static}main(String[] args)
    }

    Class tdItem{
        tdItem(String itemDesc, String date, Boolean mark)
    }

    +Class GuiController{
        +{static}addList(String title)
        +{static}addItem(File file, ArrayList<tdItem> tdList)
        +{static}delItem(File file, ArrayList<tdItem> tdList)
        +{static}editListDesc(tdItem item, ArrayList<tdItem> tdlist)
        +{static}editDate(tdItem item, ArrayList<tdItem> tdlist)
        +{static}markCom(tdItem item, ArrayList<tdItem> tdList)
        +{static}displayAll(File file, ArrayList<tdItem> tdList)
        +{static}displayIncomplete(File file, ArrayList<tdItem> tdList)
        +{static}displayComplete(File file, ArrayList<tdItem> tdList)
        +{static}saveListItems(File file, ArrayList<tdItem> tdList)
        +{static}loadList()
    }
}
@enduml