@startuml
'https://plantuml.com/class-diagram

package ucf.assignments{

    GuiController *-- tdItem
    App -- GuiController

    +Class App{
        +start(Stage stage)
        +{static}main(String[] args)
    }

    +Class tdItem{
        -SimpleStringProperty desc
        -SimpleStringProperty date
        -CheckBox status

        tdItem(String desc, String date)
        +getDesc()
        +setDesc(String desc)
        +getDate()
        +setDate(String date)
        +getStatus()
        +setStatus(Checkbox status)
    }

    +Class GuiController{
        DatePicker datePicker;
        -TextArea descBox;
        -TableView<Item> tableOfList;
        -TableColumn<Item, String> descCol;
        -TableColumn<Item, String> dateCol;
        -TableColumn<Item, CheckBox> statusCol;

        +ObservableList<Item> tdList
        +ObservableList<Item> loadList

        +FileChooser fileChooser

        +initialize(URL location, ResourceBundle resources)
        addItem(ActionEvent event)
        deleteItem(ActionEvent event)
        clearList(ActionEvent event)
        editItem(ActionEvent event)
        displayAll(ActionEvent event)
        displayComp(ActionEvent event)
        displayIncomplete(ActionEvent event)
        saveList(ActionEvent event)
        loadList(ActionEvent event)
        exit(ActionEvent event)
        +dateValidator(String date)
        +AlertDisplay(String title, String message)
    }

    +Class TestCode{
        +{static}addItem(String desc, String date)
        +{static}deleteItem(Integer index, ArrayList<Item> list)
        +{static}clearList(ArrayList<Item> list)
        +{static}editItem(String original, String edited)
        +{static}displayAll(ArrayList<Item> list)
        +{static}displayComp(ArrayList<Item> list)
        +{static}displayIncomplete(ArrayList<Item> list)
        +{static}saveList(String path, ArrayList<Item> list)
        +{static}loadList(String path, ArrayList<Item> list)





    }
}
@enduml